[versions]
kotlin = "1.6.10"
dokka = "1.5.30"
room = "2.4.1"
coroutines = "1.6.0"
exoplayer = "2.16.1"
lifecycle = "2.4.0"
navigation = "2.3.5"
constraint = "2.1.3"
androidx-core = "1.7.0"
material = "1.5.0"
androidx-browser = "1.4.0"
activity-ktx = "1.4.0"
appcompat = "1.4.1"
fragment-ktx = "1.4.0"
legacy = "1.0.0"
recyclerview = "1.2.1"
webkit = "1.4.0"
timber = "5.0.1"
joda-time = "2.10.13"
jsoup = "1.14.3"
junit = "4.13.2"
ext-junit = "1.1.3"
expresso-core = "3.4.0"
robolectric = "4.7.3"
kotlin-junit = "1.6.10"
assertj = "3.21.0"
coroutines-test = "1.5.2"
kovenant = "3.3.0"
mcxiaoke = "0.5.5"
zeroturnaround = "1.14"
media2 = "1.2.1"
media = "1.6.0"
viewpager2 = "1.0.0"
work-runtime = "2.7.1"
fuel = "2.3.1"
nanohttpd = "master-SNAPSHOT"

[libraries]
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
dokka-gradle = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
exoplayer-core = { group = "com.google.android.exoplayer", name = "exoplayer-core", version.ref = "exoplayer" }
exoplayer-ui = { group = "com.google.android.exoplayer", name = "exoplayer-ui", version.ref = "exoplayer" }
exoplayer-mediasession = { group = "com.google.android.exoplayer", name = "extension-mediasession", version.ref = "exoplayer" }
exoplayer-extension-media2 = { group = "com.google.android.exoplayer", name = "extension-media2", version.ref = "exoplayer" }
exoplayer-workmanager = { group = "com.google.android.exoplayer", name = "extension-workmanager", version.ref = "exoplayer" }
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-vmsavedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version = "2.2.0" }
lifecycle-compiler = { group = "androidx.lifecycle", name = "lifecycle-compiler", version.ref = "lifecycle" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidx-browser" }
constraint-layout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraint" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx" }
legacy-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacy" }
legacy-ui = { group = "androidx.legacy", name = "legacy-support-core-ui", version.ref = "legacy" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
joda-time = { group = "joda-time", name = "joda-time", version.ref = "joda-time" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "ext-junit" }
expresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "expresso-core" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
kotlin-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin-junit" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-test" }
kovenant-base = { group = "nl.komponents.kovenant", name = "kovenant", version.ref = "kovenant" }
kovenant-android = { group = "nl.komponents.kovenant", name = "kovenant-android", version.ref = "kovenant" }
kovenant-combine = { group = "nl.komponents.kovenant", name = "kovenant-combine", version.ref = "kovenant" }
kovenant-core = { group = "nl.komponents.kovenant", name = "kovenant-core", version.ref = "kovenant" }
kovenant-functional = { group = "nl.komponents.kovenant", name = "kovenant-functional", version.ref = "kovenant" }
kovenant-jvm = { group = "nl.komponents.kovenant", name = "kovenant-jvm", version.ref = "kovenant" }
mcxiaoke-async = { group = "com.mcxiaoke.koi", name = "async", version.ref = "mcxiaoke" }
mcxiaoke-core = { group = "com.mcxiaoke.koi", name = "core", version.ref = "mcxiaoke" }
zeroturnaround = { group = "org.zeroturnaround", name = "zt-zip", version.ref = "zeroturnaround" }
media2-session = { group = "androidx.media2", name = "media2-session", version.ref = "media2" }
media2-player = { group = "androidx.media2", name = "media2-player", version.ref = "media2" }
androidx-media = { group = "androidx.media", name = "media", version.ref = "media" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
androidx-work-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-runtime" }
rtl-viewpager = { group = "com.duolingo.open", name = "rtl-viewpager", version = "1.0.3" }
pdf-viewer = { group = "com.github.barteksc", name = "android-pdf-viewer", version = "2.8.2" }
photoview = { group = "com.github.chrisbanes", name = "PhotoView", version = "2.3.0" }
shopgun-utils = { group = "com.shopgun.android", name = "utils", version = "1.0.9" }
fuel-android = { group = "com.github.kittinunf.fuel", name = "fuel-android", version.ref = "fuel" }
fuel-core = { group = "com.github.kittinunf.fuel", name = "fuel", version.ref = "fuel" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version = "1.6.10" }
nanohttpd-core = { group = "com.github.edrlab.nanohttpd", name = "nanohttpd", version.ref = "nanohttpd" }
nanohttpd-nanolets = { group = "com.github.edrlab.nanohttpd", name = "nanohttpd-nanolets", version.ref = "nanohttpd" }
pdfium-android = { group = "com.github.barteksc", name = "pdfium-android", version = "1.8.2" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version = "1.0.0" }
androidx-paging = { group = "androidx.paging", name = "paging-runtime-ktx", version = "3.1.1" }
picasso = { group = "com.squareup.picasso", name = "picasso", version = "2.71828" }

kotlin-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version = "1.7.10" }


[bundles]
room = ["room-runtime", "room-ktx"]
exoplayer = ["exoplayer-core", "exoplayer-ui", "exoplayer-mediasession", "exoplayer-extension-media2", "exoplayer-workmanager"]
coroutines = ["coroutines-core", "coroutines-android"]
lifecycle = ["lifecycle-livedata", "lifecycle-runtime", "lifecycle-viewmodel", "lifecycle-vmsavedstate"]
navigation = ["navigation-fragment", "navigation-ui"]
mcxiaoke = ["mcxiaoke-async", "mcxiaoke-core"]
media2 = ["media2-session", "media2-player"]
fuel = ["fuel-android", "fuel-core"]
nanohttpd = ["nanohttpd-core", "nanohttpd-nanolets"]
kovenant = ["kovenant-base", "kovenant-android", "kovenant-combine", "kovenant-core", "kovenant-functional", "kovenant-jvm"]
test-frameworks = ["junit", "ext-junit", "expresso-core", "robolectric", "kotlin-junit", "assertj", "coroutines-test"]

[plugins]